// DO NOT EDIT: Code generated by matcha from home.matcha

import gleam/string_builder.{StringBuilder}
import gleam/list

import slaw/templates/header

pub fn render_builder(name name: String) -> StringBuilder {
    let builder = string_builder.from_string("")
    let builder = string_builder.append(builder, "<!DOCTYPE html>
<html>

<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>slaw</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='/assets/main.css'>
    <script src='main.js'></script>
</head>

<body>
    <!-- TODO: This renders the header template each time the page is loaded, 
        instead of just baking its contents right into the home template,
        which is worse?? i think??? -->
        ")
    let builder = string_builder.append(builder, header.render())
    let builder = string_builder.append(builder, "

    <main>
                <h1>🌷 hey ")
    let builder = string_builder.append(builder, name)
    let builder = string_builder.append(builder, "!</h1>
    </main>
</body>

</html>")

    builder
}

pub fn render(name name: String) -> String {
    string_builder.to_string(render_builder(name: name))
}
